/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package berna;

/**
 *
 * @author User
 */
public class Menubar extends javax.swing.JFrame {

    /**
     * Creates new form Menubar
     */
    public Menubar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuventana = new javax.swing.JMenu();
        menucolores = new javax.swing.JMenu();
        itemMenucolorVentana1 = new javax.swing.JMenuItem();
        itemMenucoloresVentana2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMenusalir = new javax.swing.JMenuItem();
        menulabel = new javax.swing.JMenu();
        menucoloreslabel = new javax.swing.JMenu();
        itemMenucolorlabel1 = new javax.swing.JMenuItem();
        itemMenuMenucloreslabel2 = new javax.swing.JMenuItem();
        menuimagen = new javax.swing.JMenu();
        itemMenuimagen1 = new javax.swing.JMenuItem();
        itemMenuimagen = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        itemMenuCreado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        menuventana.setText("venrtana");
        jMenuBar1.add(menuventana);

        menucolores.setText("label");

        itemMenucolorVentana1.setText("jMenuItem1");
        menucolores.add(itemMenucolorVentana1);

        itemMenucoloresVentana2.setText("jMenuItem2");
        menucolores.add(itemMenucoloresVentana2);
        menucolores.add(jSeparator1);

        itemMenusalir.setText("jMenuItem3");
        menucolores.add(itemMenusalir);

        jMenuBar1.add(menucolores);

        menulabel.setText("about");

        menucoloreslabel.setText("jMenu1");
        menulabel.add(menucoloreslabel);

        itemMenucolorlabel1.setText("jMenuItem4");
        menulabel.add(itemMenucolorlabel1);

        itemMenuMenucloreslabel2.setText("jMenuItem5");
        menulabel.add(itemMenuMenucloreslabel2);

        menuimagen.setText("jMenu1");

        itemMenuimagen1.setText("jMenuItem1");
        menuimagen.add(itemMenuimagen1);

        itemMenuimagen.setText("jMenuItem2");
        menuimagen.add(itemMenuimagen);

        menuAbout.setText("jMenu2");

        itemMenuCreado.setText("jMenuItem3");
        menuAbout.add(itemMenuCreado);

        menuimagen.add(menuAbout);

        menulabel.add(menuimagen);

        jMenuBar1.add(menulabel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menubar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuCreado;
    private javax.swing.JMenuItem itemMenuMenucloreslabel2;
    private javax.swing.JMenuItem itemMenucolorVentana1;
    private javax.swing.JMenuItem itemMenucoloresVentana2;
    private javax.swing.JMenuItem itemMenucolorlabel1;
    private javax.swing.JMenuItem itemMenuimagen;
    private javax.swing.JMenuItem itemMenuimagen1;
    private javax.swing.JMenuItem itemMenusalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menucolores;
    private javax.swing.JMenu menucoloreslabel;
    private javax.swing.JMenu menuimagen;
    private javax.swing.JMenu menulabel;
    private javax.swing.JMenu menuventana;
    // End of variables declaration//GEN-END:variables
}
